log_info:
  database_name: test_database_1
  keep_local_copy: true
  robot_id: 1
sql_database:
  host: database-2.csozaa62oxle.us-east-1.rds.amazonaws.com
  password: adamhamden
  port: 3306
  user: masterUsername
